# Site settings
title: Concurrency Theory
email: info@concurrency-theory.org
description: >- # this means to ignore newlines until "baseurl:"
  Let's tame some concurrent and distributed systems!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
theme: "just-the-docs"
plugins:
  - jekyll-redirect-from

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

collections:
  organizations:
    permalink: "/:collection/:path/"
    output: true
  events:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    organizations:
      name: Organizations
    events:
      name: Events

color_scheme: concur

# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/benkeks/concurrency-theory.org" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
