name: Build and deploy jekyll page

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  jekyll-page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - run: bundle exec jekyll build
      - name: Deploy CI
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr
          path: _site/
          remote_path: ${{ secrets.CI_DEPLOY_PATH }}
          remote_host: ${{ secrets.CI_DEPLOY_HOST }}
          remote_user: ${{ secrets.CI_USER }}
          remote_key: ${{ secrets.CI_PRIVKEY }}

